/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Particle_Particle */

#ifndef _Included_Particle_Particle
#define _Included_Particle_Particle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Particle_Particle
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Particle_Particle_update
  (JNIEnv *, jobject);

/*
 * Class:     Particle_Particle
 * Method:    applyForce
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_Particle_Particle_applyForce
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
