/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pack_ParticleSystem */

#ifndef _Included_Pack_ParticleSystem
#define _Included_Pack_ParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pack_ParticleSystem
 * Method:    setForces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pack_ParticleSystem_setForces
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
