/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pack_Particle_Particle */

#ifndef _Included_Pack_Particle_Particle
#define _Included_Pack_Particle_Particle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pack_Particle_Particle
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pack_Particle_Particle_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
